### ISSUE TITLE
Spreading Factor Increases on OTAA with ADR off

### ISSUE THREAD

**Issue by tkerby** [kizniche/ttgo-tbeam-ttn-tracker#10]
I've noticed that over time the data rate/SF increases up to SF10 with ADR turned off (set to 0) in the config file. I'm using OTAA join and have tried LMIC 2.3.2 and 3.0.99 from the MCCI repositories. I've tried setting interrupts both on and off in LMIC to see if its timing related.

See image below from the gateway. The number of packets received before the data rate increases is variable but I see some rejoin failed messages on the screen and message discarded (presumably through airtime constraints) in operation.

![image](https://user-images.githubusercontent.com/3738500/68295464-63519800-008a-11ea-89ff-f160a294fc7e.png)

**Comment by tkerby** [comment]
My thought on this is that to receive link dead messages in the lcd, link checking must be enabled. Could this be causing the SF to increase even with ADR off?

**Comment by tkerby** [comment]
I made a mod to turn off link checks but I'm not seeing an improvement and it still increases SF

void ttn_adr(bool enabled) {
    LMIC_setAdrMode(enabled);
    LMIC_setLinkCheckMode(!enabled);
}

**Comment by ctandi** [comment]
@tkerby Have you found a fix by now? I'm running into the same issue. Thanks.

**Comment by pooley92** [comment]
I am also experiencing this too. Changing the DR_SF has no effect and it cycles through the data rates. Seems like it’s ADR.

**Comment by Migi5700** [comment]
Hi everyone,
I have the same problem here, the DR_SF goes up and down.
Changing the DR_SF in the configuration.h file has also no effect, it is always starting at SF7.
I'm not sure if this is ADR, because I never saw a downlink-message, but I dont know if you see the ADR-messages at the TTN traffic-console.
Anyone can help :-)
Greetings

**Comment by ciphermaster** [comment]
Hi everyone.
Same issue here. I have tried everything but the SF remains on SF7. It does not matter if I have enabled ADR or Not.
I have also disabled LMIC_setLinkCheckMode(0) but no change. LMIC Library is on the latest version.

**Comment by BjoernSch** [comment]
> I made a mod to turn off link checks but I'm not seeing an improvement and it still increases SF
> 
> void ttn_adr(bool enabled) {
> LMIC_setAdrMode(enabled);
> LMIC_setLinkCheckMode(!enabled);
> }

This enables link checking if ADR is disabled.

**Comment by gougakos** [comment]
> Hi everyone. Same issue here. I have tried everything but the SF remains on SF7. It does not matter if I have enabled ADR or Not. I have also disabled LMIC_setLinkCheckMode(0) but no change. LMIC Library is on the latest version.

have you to fixed the stuck SF7 issue. No matter what i try it always sends only to sf7. I opened  [https://github.com/kizniche/ttgo-tbeam-ttn-tracker/issues/55](url) regarding this.
