### ISSUE TITLE
cayenne mydevices device

### ISSUE THREAD

**Issue by chrkan** [kizniche/ttgo-tbeam-ttn-tracker#15]
Hallo Tanks for the great work, 
can you tell me witch device you use vor cayenne mydevices to show the track in a map?

thanks

**Comment by kizniche** [comment]
I don't quite understand the question. Can you elaborate?

**Comment by chrkan** [comment]
In your skatch there is the option PAYLOAD_USE_CAYENNE, my question is how you can configure this at https://cayenne.mydevices.com/ or which device you select there. Or did I misunderstand the whole thing?

**Comment by kizniche** [comment]
This option is to use the Cayanne payload format for thethingsnetwork decoder rather than the supplied custom decoder.

![Screenshot_20200212-131254_Brave](https://user-images.githubusercontent.com/838427/74363970-a44bfd80-4d99-11ea-8a8a-3a8f4850648e.jpg)
