### ISSUE TITLE
Sat Lock. Wait for x sats

### ISSUE THREAD

**Issue by dafyddhirst** [kizniche/ttgo-tbeam-ttn-tracker#21]
Is there any possible way once it has lock to wait for x satellites to improve the lock accuracy?
Thanks

**Comment by kizniche** [comment]
You should be able to edit this line:

https://github.com/kizniche/ttgo-tbeam-ttn-tracker/blob/f4b7577d050a76365159d5ae9216cae2d62ebc51/main/main.ino#L280

to this:

```c#
    if (3 < gps_sats() && 0 < gps_hdop() && gps_hdop() < 50 && gps_latitude() != 0 && gps_longitude() != 0) {
```

Changing ```3 < gps_sats()``` to whatever number of satellites you want the lock to be greater than in order to send.
