### ISSUE TITLE
The Things Stack v3 - Frame Counter does not reset

### ISSUE THREAD

**Issue by Quas7** [kizniche/ttgo-tbeam-ttn-tracker#44]
Hi,

it looks like that the v2->v3 transition makes it more complicated to "ignore" the framecounter in APB mode.
I will now try to reset the fcnt with LMIC_reset() or LMIC.seqnoUp = 0 during setup().

Could be related to my problem in #43

**Comment by Quas7** [comment]
after some digging I found `static void ttn_set_cnt()` is overruling all my attempts to get the frame counter back to zero. ;)

**Comment by Quas7** [comment]
solved my issue with the frame counter and also found ttn_erase_prefs() accessable via button press.
Maybe add the erase function somewhere in the readme as it is required to be done for migrating v2-->v3 (or switching applications on the TTN).

**Comment by kizniche** [comment]
Added comment in configuration.h
