### ISSUE TITLE
Compiling fails in axp192Init

### ISSUE THREAD

**Issue by simonszu** [kizniche/ttgo-tbeam-ttn-tracker#50]
I am trying to compile the project with platformIO after entering all config stuff. However, the compilation run is failing:

```
Compiling .pio/build/esp32/lib208/MCCI LoRaWAN LMIC library/lmic/lmic.c.o
/media/Storage/home/Datengrab/Elektronik/PlatformIO/t-beam/ttgo-tbeam-ttn-tracker/main/main.ino: In function 'void axp192Init()':
/media/Storage/home/Datengrab/Elektronik/PlatformIO/t-beam/ttgo-tbeam-ttn-tracker/main/main.ino:285:17: error: 'class AXP20X_Class' has no member named 'isChargeing'
         if (axp.isChargeing()) {
                 ^
Compiling .pio/build/esp32/lib208/MCCI LoRaWAN LMIC library/lmic/lmic_as923.c.o
*** [.pio/build/esp32/src/main.ino.cpp.o] Error 1
==================================================================================== [FAILED] Took 16.54 seconds ====================================================================================
```
At a first glance at https://github.com/lewisxhe/AXP202X_Library/blob/master/src/axp20x.h#L689 i would say that the root cause is simply an e at the wrong place. But since the last commit to ` main.ino` was quite some time ago, and no one was having this issue yet (according to the issue tracker) i am not entirely sure about that, and therefore creating this issue.

**Comment by kizniche** [comment]
Thanks. I'll commit a fix for this soon.
