### ISSUE TITLE
Information, SH1106 looks like SSD1306 ;-)

### ISSUE THREAD

**Issue by Internetwurm** [kizniche/ttgo-tbeam-ttn-tracker#7]
Hello Kizniche,

maybe more a general display issue and not really related to your faboulus work here.
But i guess some people stumbble over that and get anoyed about it.

There exist a different 1.3" OLED with a different chip SH1106.
You get scrambled Graphics with this program "out of the box".

I "adjusted" screen.h to make it work because it also there but unused:

add a
#define SH1106_ADDRESS 0x03C  // i didn´t searched for the real right place, sorry for my lazyness

on top of the header file

change
SSD1306Wire * display;  // better to uncomment maybe
to 
SH1106Wire * display;

change 
display = new SSD1306Wire(SSD1306_ADDRESS, I2C_SDA, I2C_SCL); // better to uncomment maybe

to
display = new SH1106Wire(SH1106_ADDRESS, I2C_SDA, I2C_SCL);

save and compile and upload and smile.
Maybe you could consider it in anyway to include this to only uncomment for not as much expirenced people to get it to work if first try fails.

The rest seems to be fine and of good quality.

Nice work!

regards

**Comment by kizniche** [comment]
Thanks. I'll add an option to select which display to use.
