### ISSUE TITLE
AXP192 Status

### ISSUE THREAD

**Issue by tkerby** [kizniche/ttgo-tbeam-ttn-tracker#9]
I see you’re looking for interrupts from the battery charging circuitry but you’re not displaying or outputting the status. 

The AXP192 offers full fuel gauge capabilities. It would be great to include a battery charging and level icon on the top bar.

**Comment by harryd100** [comment]
+1

**Comment by kizniche** [comment]
I don't have a battery to test this with, but I see a print line was added in your PR #11. I'll look into other code for how battery icons are created.

**Comment by kizniche** [comment]
Added to latest version
